### ISSUE TITLE
Android: date choice modal too smart

### ISSUE THREAD

**Issue by Thzx** [impfen/apps-inoeg#113]
1. Android Chromium browsers
2. Go to https://demo.impfterm.in/finder/appointment/
3. Get to choice of appointments
4. Click date choice (day, month, year)

The date choice modal seems to include limits of available dates. Okay, but that means switching months changes the day and vice versa
![Screenshot_20220207-110001_Chrome Beta](https://user-images.githubusercontent.com/2153595/152768357-42244b8e-febf-4834-8aa9-9806b9b0ef11.jpg)

Examples:
- I can see January / April on the date-choice wheel, switching month to them yields the first / last available day (in Feb / March)
- 13 Feb, switching to March yields 9 March

Expected behavior: allow entry of any date, get feedback later

**Comment by Thzx** [comment]
I can't easily produce an exhaustive list of examples.

I would prefer, at least optionally, direct entry of date.

**Comment by benbender** [comment]
@Thzx this is the native-ui of the phone/desktop. On most desktops you would have both options, but I opted for the native ui, as it works (mostly) well on most systems and is a already known system for most people. Would rather not change it to something custom.

**Comment by Thzx** [comment]
That is hardly ever used by websites and apps I've seen in the last several years.

Anyways, my main issue wasn't the modal but the erratic behavior I described in the examples, presumably due to the limited time range of the appointments.

Sorry, I guess the pic inside the issue report wasn't the best idea.

**Comment by Thzx** [comment]
A video may help. Anyways, it's not that pressing.
