### ISSUE TITLE
Adjust questionnaire

### ISSUE THREAD

**Issue by topialla** [impfen/apps-inoeg#120]
Mit Mehrfachauswahl 
- #119 

verfügbar, muss der Fragebogen zu beginn überarbeitet werden.

z.B.

- Schwangerschaft muss von "unter 30 Jahre?" getrennt werden

**Comment by benbender** [comment]
Erster Annäherung als Stategraph, auf dem ich as wohl zukünftig aufbaue:
https://stately.ai/viz/7c7ddc97-fa66-4b10-812d-0b0474af6582
https://stately.ai/registry/machines/7c7ddc97-fa66-4b10-812d-0b0474af6582.png

**Comment by benbender** [comment]
Offene Fragen:
- Muss/soll für U12 Schwangerschaft & Booster abgefragt werden?
- Evtl. besser Alter oder Geburtstag abfragen anstatt als select/radio 5 Optionen anzubieten?

**Comment by topialla** [comment]
Alter sollten wir nicht exakt fragen, weil nicht datensparsam und das brauchen wir nicht.
Wir Fragen Altersgruppe.
Evtl mit Schieber mit einem Stop je Gruppe? (da fehlt mir die Erfahrung was gut funktioniert).

Erstmal bitte Radiobuttons, weil vermutlich am breitesten in Browsern verfügbar.

"Wie alt sind Sie bzw. die zu Impfende Person?"

Älter als 30, 12–30 Jahre , 5–12 Jahre, jünger als 5 Jahre

Bei Ü12: Sind Sie bzw. die zu impfende Person schwanger?

Alternativ:
Flow starten mit "Buchen Sie für sich oder für Angehörige?" (MVP erstmal @bkastl)

Dann ist die Person schonmal Ü16

U12 muss Booster erstmal nicht, später vermutlich schon abgefragt werden.

Wenn es lokal mit CWA-Immunhistorie ginge, wäre alles sooo viel Einfacher. ;-)

**Comment by benbender** [comment]
> Alter sollten wir nicht exakt fragen, weil nicht datensparsam und das brauchen wir nicht. 
Das Privatsphärethema wird ja nicht wirklich berührt, da die Daten den Browser nie verlassen, oder?

> Wir Fragen Altersgruppe. Evtl mit Schieber mit einem Stop je Gruppe? (da fehlt mir die Erfahrung was gut funktioniert).
Schieber geht nicht nativ, wenn der interval nicht gleichmäßig ist. Die Idee würde ich daher verwerfen, weil das mit Assistenzsystemen für Accessibility sonst ein Alptraum wird.

> Erstmal bitte Radiobuttons, weil vermutlich am breitesten in Browsern verfügbar.
Select + Radio-Buttons sind nativ und überall verfügbar. Radio-Buttons haben den Vorteil, dass man alle Optionen auf einen Blick hat. Der Select (aka "DropDown") das es weniger Auswahloptionen auf einmal sind. Das sind reine UX-Fragen und weniger Implementierung. Die ändert sich quasi nicht.

> Wenn es lokal mit CWA-Immunhistorie ginge, wäre alles sooo viel Einfacher. ;-)
Leider auch nicht, so lange die Daten in den Impfzertifikaten nicht eindeutig und klar sind. Und das sind sie zumindest bis vor einer Woche für bspw. Genesene und J&J-Geimpfte nicht. Handling war das letzte Jahr in solchen Fällen bundeslandabhängig (yes, really...!)

**Comment by topialla** [comment]
> > Alter sollten wir nicht exakt fragen, weil nicht datensparsam und das brauchen wir nicht.
> 
> Das Privatsphärethema wird ja nicht wirklich berührt, da die Daten den Browser nie verlassen, oder?
> 
Das stimmt, ist den Leuten aber nicht klar, gibt potentiell unnötige Diskussionen

> > Wir Fragen Altersgruppe. Evtl mit Schieber mit einem Stop je Gruppe? (da fehlt mir die Erfahrung was gut funktioniert).
> 
> Schieber geht nicht nativ, wenn der interval nicht gleichmäßig ist. Die Idee würde ich daher verwerfen, weil das mit Assistenzsystemen für Accessibility sonst ein Alptraum wird.
> 
> > Erstmal bitte Radiobuttons, weil vermutlich am breitesten in Browsern verfügbar.
> 
> Select + Radio-Buttons sind nativ und überall verfügbar. Radio-Buttons haben den Vorteil, dass man alle Optionen auf einen Blick hat. Der Select (aka "DropDown") das es weniger Auswahloptionen auf einmal sind. Das sind reine UX-Fragen und weniger Implementierung. Die ändert sich quasi nicht.
> 
Dann Radiobuttons bitte. Wenn es irgendwann kompliziertere Altersdinge gibt müssen wir doch exaktes Alter abfragen.
> > Wenn es lokal mit CWA-Immunhistorie ginge, wäre alles sooo viel Einfacher. ;-)
> 
> Leider auch nicht, so lange die Daten in den Impfzertifikaten nicht eindeutig und klar sind. Und das sind sie zumindest bis vor einer Woche für bspw. Genesene und J&J-Geimpfte nicht. Handling war das letzte Jahr in solchen Fällen bundeslandabhängig (yes, really...!)
> 
> EDIT: Ich denke, ich hab aber ne Idee, wie wir's erstmal machen. Spannend sind jetzt noch die impliziten Folgen für v.a. die Aufklärunsgtexte/Links bei der Buchung. Da fehlen dann Inhalte.

Die Aufklärungstexte ändern sich quasi nicht @benbender. Das ist für alle vektorimpfstoffe der gleiche, für die mRNAs auch. Wenn Novavax kommt gibts nochmal neues.
Das ist schon so aktuell


| Impfstoff_ID | Hersteller                   | Wirkstoff                          | Fullname                                                                  | Category | InformationSheet_DE                                                                                                                        | Anamnesis_consent_DE                                                                                                                  | Information_and_Anamnesis_consent_EN                                                                                                             | InformationSheet_DE_plain                                                                                                                                        | Anamnesis_consent_DE_plain                                                                                                                          |
|--------------|------------------------------|------------------------------------|---------------------------------------------------------------------------|----------|--------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| AZ           | AstraZeneca                  | (Vaxzevria®)                       | AstraZeneca (Vaxzevria®)                                                  | vector   | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-de.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Einwilligung-de.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-Englisch.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-leichte-Sprache_Vaxzevri.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Anamnesebogen-leichte-Sprache.pdf?__blob=publicationFile |
| BT           | BioNTech/Pfizer              | (Comirnaty®)                       | BioNTech/Pfizer (Comirnaty®)                                              | mRNA     | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-de.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Einwilligung-de.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-Englisch.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-leichte-Sprache.pdf?__blob=publicationFile                          | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Anamnesebogen-leichte-Sprache.pdf?__blob=publicationFile                 |
| JJ           | Johnson & Johnson            | (Janssen®)                         | Johnson & Johnson (Janssen®)                                              | vector   | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-de.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Einwilligung-de.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-Englisch.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-leichte-Sprache_Janssen.pdf?__blob=publicationFile  | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Anamnesebogen-leichte-Sprache.pdf?__blob=publicationFile |
| MD           | Moderna                      | (Spikevax®)                        | Moderna (Spikevax®)                                                       | mRNA     | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-de.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Einwilligung-de.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-Englisch.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-leichte-Sprache.pdf?__blob=publicationFile                          | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Anamnesebogen-leichte-Sprache.pdf?__blob=publicationFile                 |
| BTch         | BioNTech/Pfizer              | (Comirnaty®) für 5- bis 11-jährige | BioNTech/Pfizer (Comirnaty®) für 5- bis 11-jährige                        | mRNA     | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-de.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Einwilligung-de.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-Englisch.pdf?__blob=publicationFile                 | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Aufklaerungsbogen-leichte-Sprache.pdf?__blob=publicationFile                          | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19/Anamnesebogen-leichte-Sprache.pdf?__blob=publicationFile                 |
| mRNA         | BioNTech/Pfizer bzw. Moderna | (Comirnaty®) bzw. (Spikevax®)      | ein mRNA-Impfstoff, BioNTech/Pfizer (Comirnaty®) oder Moderna (Spikevax®) | mRNA     | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-de.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Einwilligung-de.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-Englisch.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Aufklaerungsbogen-leichte-Sprache_Vaxzevri.pdf?__blob=publicationFile | https://www.rki.de/DE/Content/Infekt/Impfen/Materialien/Downloads-COVID-19-Vektorimpfstoff/Anamnesebogen-leichte-Sprache.pdf?__blob=publicationFile |

**Comment by benbender** [comment]
done via feat/next.
