### ISSUE TITLE
Datumsformat der Terminkachel

### ISSUE THREAD

**Issue by topialla** [impfen/apps-inoeg#125]
Auf der Terminkachel beim Auswählen des Termins wird das Datum als

> am `ddd, dd. MMMM` (Bsp: Fr, 11. Februar)

Angezeigt

Jahr kann zunächst weggelassen werden, da das Kalenderjahr ein junges ist. (Jahr ist nicht MVP-Relevant)

Ebenso ist so das Problem Tag-Monat-Jahr Reihenfolge in verschiedenen Sprachen dann erstmal gelöst

(Uhrzeit bleibt, wie sie ist),

Kachel für die Buchungsbestätigung kann mit Jahr bleiben, wenn einfacher.

**Comment by topialla** [comment]
Wenn voller Monat zu lang, auch 3-Buchstaben-Format möglich

**Comment by benbender** [comment]
ist 3-Buchstaben geworden :)
