### ISSUE TITLE
Einbindung Novavax

### ISSUE THREAD

**Issue by bkastl** [impfen/apps-inoeg#136]
Es gibt einen neuen Impfstoff: Nuvaxovid (Novavax)

Eigenschaften:
- ab 18 Jahren
- nicht schwanger
- (eigentlich auch nur für Personen im medizinischen Bereich, wird aber aktuell nicht besonders stark verfolgt)

**Comment by benbender** [comment]
d.h. konkret es ist ein weiterer Impfstoff für alle ohne besondere Voraussetzung zur Zeit, richtig? D.h. am Questionaire ändert sich nichts und der neue Impfstoff muss, mit den entsprechenden Aufklärungslinks usw (👀 @topialla), in die Datenstrukturen eingetragen werden?

**Comment by topialla** [comment]
Aufklärungslinks etc siehe 
- #137 

bisher leider nur Deutsch verfügbar.

**Comment by benbender** [comment]
gemerged und in allen repos gesynced. Danke!
